SELECT TABLE_NAME AS 'Table Name' FROM INFORMATION_SCHEMA.TABLES  
WHERE Table_NAME NOT IN  
	( SELECT DISTINCT c.TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS c 
	  INNER JOIN sys.identity_columns ic  
	  ON (c.COLUMN_NAME=ic.NAME)
	) AND TABLE_TYPE ='BASE TABLE'